export const ERPEvents = {
  CLIENTE_CADASTRADO: 'CLIENTE_CADASTRADO',

  RESERVA_CRIADA: 'RESERVA_CRIADA',
  RESERVA_CONFIRMADA: 'RESERVA_CONFIRMADA',
  RESERVA_CANCELADA: 'RESERVA_CANCELADA',

  PAGAMENTO_RECEBIDO: 'PAGAMENTO_RECEBIDO',

  CONTRATO_GERADO: 'CONTRATO_GERADO',
  CONTRATO_ASSINADO: 'CONTRATO_ASSINADO',

  OS_CRIADA: 'OS_CRIADA',
  OS_CONCLUIDA: 'OS_CONCLUIDA',

  MISSAO_INICIADA: 'MISSAO_INICIADA',
  MISSAO_FINALIZADA: 'MISSAO_FINALIZADA',

  CHECKLIST_CONCLUIDO: 'CHECKLIST_CONCLUIDO'
} as const

export type ERPEventCode =
  typeof ERPEvents[keyof typeof ERPEvents]
