export const ERPEvents = {
  CLIENTE_CADASTRADO: 'CLIENTE_CADASTRADO',

  PRE_RESERVA_RECEBIDA: 'PRE_RESERVA_RECEBIDA',
  PRE_RESERVA_EM_ANALISE: 'PRE_RESERVA_EM_ANALISE',
  PRE_RESERVA_AJUSTE_SOLICITADO: 'PRE_RESERVA_AJUSTE_SOLICITADO',
  PRE_RESERVA_APROVADA: 'PRE_RESERVA_APROVADA',
  PRE_RESERVA_RECUSADA: 'PRE_RESERVA_RECUSADA',
  PRE_RESERVA_CONVERTIDA_EM_PROPOSTA: 'PRE_RESERVA_CONVERTIDA_EM_PROPOSTA',

  PROPOSTA_ENVIADA: 'PROPOSTA_ENVIADA',
  PROPOSTA_ENVIO_CANCELADO: 'PROPOSTA_ENVIO_CANCELADO',
  PROPOSTA_ACEITA: 'PROPOSTA_ACEITA',
  PROPOSTA_RECUSADA: 'PROPOSTA_RECUSADA',
  CLIENTE_DADOS_COMPLETOS: 'CLIENTE_DADOS_COMPLETOS',

  RESERVA_CRIADA: 'RESERVA_CRIADA',
  RESERVA_CONFIRMADA: 'RESERVA_CONFIRMADA',
  RESERVA_CANCELADA: 'RESERVA_CANCELADA',

  PAGAMENTO_RECEBIDO: 'PAGAMENTO_RECEBIDO',

  CONTRATO_GERADO: 'CONTRATO_GERADO',
  CONTRATO_ASSINADO: 'CONTRATO_ASSINADO',

  OS_CRIADA: 'OS_CRIADA',
  OS_CONCLUIDA: 'OS_CONCLUIDA',

  MISSAO_INICIADA: 'MISSAO_INICIADA',
  MISSAO_FINALIZADA: 'MISSAO_FINALIZADA',

  CHECKLIST_CONCLUIDO: 'CHECKLIST_CONCLUIDO'
} as const

export type ERPEventCode =
  typeof ERPEvents[keyof typeof ERPEvents]
