-- Primeira entrega do Funil Comercial: oportunidades e histórico de etapas.

create table if not exists public.oportunidades (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  empresa_id uuid references public.empresas(id) on delete cascade,
  cliente_id uuid references public.clientes(id) on delete set null,
  nome_contato text not null,
  celular text not null,
  email text,
  origem text not null default 'Não informada',
  interesse text,
  data_evento date,
  quantidade_convidados integer check (
    quantidade_convidados is null or quantidade_convidados > 0
  ),
  valor_estimado numeric(12, 2) not null default 0 check (valor_estimado >= 0),
  etapa text not null default 'Novo contato' check (
    etapa in (
      'Novo contato',
      'Em atendimento',
      'Orçamento enviado',
      'Negociação',
      'Fechado',
      'Perdido'
    )
  ),
  proximo_contato date,
  motivo_perda text,
  observacoes text,
  responsavel_id uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.oportunidade_historico (
  id uuid primary key default gen_random_uuid(),
  oportunidade_id uuid not null references public.oportunidades(id) on delete cascade,
  usuario_id uuid references auth.users(id) on delete set null default auth.uid(),
  tipo text not null check (tipo in ('Criação', 'Etapa', 'Observação')),
  descricao text not null,
  etapa_anterior text,
  etapa_nova text,
  created_at timestamptz not null default now()
);

create index if not exists oportunidades_etapa_idx
on public.oportunidades(etapa);

create index if not exists oportunidades_proximo_contato_idx
on public.oportunidades(proximo_contato);

create index if not exists oportunidades_cliente_idx
on public.oportunidades(cliente_id);

create index if not exists oportunidade_historico_oportunidade_idx
on public.oportunidade_historico(oportunidade_id, created_at desc);

create or replace function public.atualizar_oportunidade_timestamp()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.registrar_historico_oportunidade()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.oportunidade_historico (
      oportunidade_id,
      usuario_id,
      tipo,
      descricao,
      etapa_nova
    ) values (
      new.id,
      coalesce(auth.uid(), new.created_by),
      'Criação',
      'Oportunidade criada no Funil Comercial.',
      new.etapa
    );
  elsif new.etapa is distinct from old.etapa then
    insert into public.oportunidade_historico (
      oportunidade_id,
      usuario_id,
      tipo,
      descricao,
      etapa_anterior,
      etapa_nova
    ) values (
      new.id,
      auth.uid(),
      'Etapa',
      'Etapa alterada de “' || old.etapa || '” para “' || new.etapa || '”.',
      old.etapa,
      new.etapa
    );
  end if;

  return new;
end;
$$;

drop trigger if exists atualizar_oportunidade_timestamp
on public.oportunidades;

create trigger atualizar_oportunidade_timestamp
before update on public.oportunidades
for each row execute function public.atualizar_oportunidade_timestamp();

drop trigger if exists registrar_historico_oportunidade
on public.oportunidades;

create trigger registrar_historico_oportunidade
after insert or update of etapa on public.oportunidades
for each row execute function public.registrar_historico_oportunidade();

alter table public.oportunidades enable row level security;
alter table public.oportunidade_historico enable row level security;

drop policy if exists "Usuários autenticados podem visualizar oportunidades"
on public.oportunidades;

create policy "Usuários autenticados podem visualizar oportunidades"
on public.oportunidades
for select to authenticated
using (true);

drop policy if exists "Usuários autenticados podem criar oportunidades"
on public.oportunidades;

create policy "Usuários autenticados podem criar oportunidades"
on public.oportunidades
for insert to authenticated
with check (created_by = auth.uid());

drop policy if exists "Usuários autenticados podem atualizar oportunidades"
on public.oportunidades;

create policy "Usuários autenticados podem atualizar oportunidades"
on public.oportunidades
for update to authenticated
using (true)
with check (true);

drop policy if exists "Usuários autenticados podem visualizar histórico comercial"
on public.oportunidade_historico;

create policy "Usuários autenticados podem visualizar histórico comercial"
on public.oportunidade_historico
for select to authenticated
using (true);

grant select, insert, update on public.oportunidades to authenticated;
grant select on public.oportunidade_historico to authenticated;
grant usage, select on sequence public.oportunidades_numero_seq to authenticated;

revoke all on function public.atualizar_oportunidade_timestamp() from public;
revoke all on function public.registrar_historico_oportunidade() from public;
