-- Segunda entrega comercial: editor de orçamentos integrado ao Funil.

create table if not exists public.orcamentos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  empresa_id uuid references public.empresas(id) on delete cascade,
  oportunidade_id uuid references public.oportunidades(id) on delete set null,
  cliente_id uuid references public.clientes(id) on delete set null,
  status text not null default 'Rascunho' check (
    status in ('Rascunho', 'Enviado', 'Aprovado', 'Recusado', 'Expirado')
  ),
  validade date,
  data_evento date,
  horario_evento text,
  data_retirada date,
  data_devolucao date,
  endereco_evento text,
  subtotal numeric(12, 2) not null default 0,
  desconto numeric(12, 2) not null default 0 check (desconto >= 0),
  acrescimos numeric(12, 2) not null default 0 check (acrescimos >= 0),
  frete numeric(12, 2) not null default 0 check (frete >= 0),
  total numeric(12, 2) not null default 0,
  observacoes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orcamento_itens (
  id uuid primary key default gen_random_uuid(),
  orcamento_id uuid not null references public.orcamentos(id) on delete cascade,
  kit_id uuid references public.kits(id) on delete set null,
  descricao text not null,
  quantidade numeric(10, 2) not null default 1 check (quantidade > 0),
  valor_unitario numeric(12, 2) not null default 0 check (valor_unitario >= 0),
  subtotal numeric(12, 2) generated always as (quantidade * valor_unitario) stored,
  created_at timestamptz not null default now()
);

create index if not exists orcamentos_oportunidade_idx
on public.orcamentos(oportunidade_id);

create index if not exists orcamentos_status_idx
on public.orcamentos(status);

create index if not exists orcamentos_validade_idx
on public.orcamentos(validade);

create index if not exists orcamento_itens_orcamento_idx
on public.orcamento_itens(orcamento_id);

create or replace function public.calcular_total_orcamento()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.subtotal := greatest(coalesce(new.subtotal, 0), 0);
  new.desconto := greatest(coalesce(new.desconto, 0), 0);
  new.acrescimos := greatest(coalesce(new.acrescimos, 0), 0);
  new.frete := greatest(coalesce(new.frete, 0), 0);
  new.total := greatest(
    new.subtotal - new.desconto + new.acrescimos + new.frete,
    0
  );
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.recalcular_orcamento_por_itens()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_orcamento_id uuid;
begin
  if tg_op = 'DELETE' then
    v_orcamento_id := old.orcamento_id;
  else
    v_orcamento_id := new.orcamento_id;
  end if;

  update public.orcamentos
  set subtotal = coalesce((
    select sum(item.subtotal)
    from public.orcamento_itens item
    where item.orcamento_id = v_orcamento_id
  ), 0)
  where id = v_orcamento_id;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists calcular_total_orcamento
on public.orcamentos;

create trigger calcular_total_orcamento
before insert or update on public.orcamentos
for each row execute function public.calcular_total_orcamento();

drop trigger if exists recalcular_orcamento_por_itens
on public.orcamento_itens;

create trigger recalcular_orcamento_por_itens
after insert or update or delete on public.orcamento_itens
for each row execute function public.recalcular_orcamento_por_itens();

alter table public.orcamentos enable row level security;
alter table public.orcamento_itens enable row level security;

drop policy if exists "Usuários autenticados podem acessar orçamentos"
on public.orcamentos;

create policy "Usuários autenticados podem acessar orçamentos"
on public.orcamentos
for all to authenticated
using (true)
with check (true);

drop policy if exists "Usuários autenticados podem acessar itens do orçamento"
on public.orcamento_itens;

create policy "Usuários autenticados podem acessar itens do orçamento"
on public.orcamento_itens
for all to authenticated
using (true)
with check (
  exists (
    select 1
    from public.orcamentos orcamento
    where orcamento.id = orcamento_id
  )
);

grant select, insert, update, delete on public.orcamentos to authenticated;
grant select, insert, update, delete on public.orcamento_itens to authenticated;
grant usage, select on sequence public.orcamentos_numero_seq to authenticated;

revoke all on function public.calcular_total_orcamento() from public;
revoke all on function public.recalcular_orcamento_por_itens() from public;
